apiVersion: v2
# renovate: datasource=github-releases depName=anthonyraymond/joal
appVersion: 2.1.37
description: JOAL is not designed to help or encourage you downloading illegal materials ! You must respect the law applicable in your country. I couldn't be held responsible for illegal activities performed by your usage of JOAL.
name: joal
# renovate: datasource=helm depName=joal repository=https://spirit-dev.github.io/helm-charts
version: "2.1.36"
icon: https://spirit-dev.github.io/helm-charts/joal/logo/joal.png
home: https://github.com/spirit-dev/helm-charts
keywords:
  - torrent
  - joal
sources:
  - https://github.com/spirit-dev/helm-charts
dependencies:
  - name: joal
    repository: https://spirit-dev.github.io/helm-charts
    version: 1.1.1
